### ISSUE TITLE
Xcode crashing

### ISSUE THREAD

**Issue by tushar66** [jeremyvizzini/MediaInfoKit#1]
Xcode is craching when I am using this framework. Can you generate a Pod for it.

**Comment by jeremyvizzini** [comment]
MediaInfoKit is still in development, I think I will add some constant keys.
I'm waiting the final version to add pod and to complete the readme file.

When I directly add mediainfolib into the main bundle, Xcode complies.
When I add it into the framework, Xcode won't compile and crashes.

I have resolved this bug by signing MediaInfoKit with my developer ID.
Can you try to do the same and let me know ?

**Comment by fooxy** [comment]
Hello,
I had the same issue as tushar66.
I tried your solution with the signing and it works.
When a first release will be available?
Thank you for the work

**Comment by jeremyvizzini** [comment]
Hi,

I have updated the code with little changes and add documentation.
Moreover, I have complete the read me file with installation guide and code example.

I tried to add cocoapods support but It doesn't work.
I just don't know how to inform cocoapods to include mediainfo.dylib :/
